export enum ScreenName {
  LANDING = 'LANDING',
  FEATURES = 'FEATURES',
  SIGNUP = 'SIGNUP',
  LOGIN = 'LOGIN',
  TARGET_AUDIENCE = 'TARGET_AUDIENCE',
  PRICING = 'PRICING',
  FAQ = 'FAQ',
  TESTIMONIALS = 'TESTIMONIALS',
  MAIN_FEATURES = 'MAIN_FEATURES',
  BOOKING = 'BOOKING',
  DASHBOARD = 'DASHBOARD',
  DASHBOARD_AGENDA = 'DASHBOARD_AGENDA',
  DASHBOARD_CLIENTS = 'DASHBOARD_CLIENTS',
  DASHBOARD_SERVICES = 'DASHBOARD_SERVICES',
  DASHBOARD_FINANCIAL = 'DASHBOARD_FINANCIAL',
  DASHBOARD_MARKETING = 'DASHBOARD_MARKETING',
  DASHBOARD_REPORTS = 'DASHBOARD_REPORTS',
  DASHBOARD_SETTINGS = 'DASHBOARD_SETTINGS',
}

// Make onNavigate optional as many routes don't pass it explicitly (using react-router hooks instead)
export interface NavProps {
  onNavigate?: (screen: ScreenName) => void;
}